### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by jellelicht** [types/npm-passport-oauth2#1]
See title of issue. Is anyone still working on this project? Any chance it could at least be uploaded to npm?
Or are there any showstoppers?

**Comment by blakeembrey** [comment]
Yes, it's alive. No, it doesn't need updating. Yes, there's showstoppers. We can't upload to NPM. See https://github.com/Microsoft/types-publisher/issues/4.

**Comment by blakeembrey** [comment]
If there is an issue with the types, please feel free to open another issue though.
